name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  push:
    branches: [preview]
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
    - uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: cloudcannon/pagefind
    - uses: actions/checkout@v3.5.2
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements_test.txt
    - name: html
      run: make html api
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy _build/html --project-name=esphome-docs
